server {
  listen 80;
  server_name _;

  root /usr/share/nginx/html;
  index index.html;

  add_header Access-Control-Allow-Origin "*" always;
  add_header Access-Control-Allow-Methods "GET, OPTIONS" always;
  add_header Access-Control-Allow-Headers "*" always;

  location = / {
    return 302 /modules/robin-tools/;
  }

  location = /healthz {
    access_log off;
    add_header Content-Type text/plain;
    return 200 'ok';
  }

  location /modules/robin-tools/ {
    rewrite ^/modules/robin-tools/(.*)$ /$1 break;
    try_files $uri $uri/ /index.html;
  }

  location / {
    try_files $uri $uri/ /index.html;
  }
}
